project:
  type: website

website:
  title: "Simon Worthington - Profile and Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mrchristian
      - icon: Mastodon
        href: https://openbiblio.social/@mrchristiang
format:
  html:
    theme: cosmo
    css: styles.css



